### PR TITLE
Feature/configure middleware

### PR DESCRIPTION
**Pull request by Keoghan**
Hi Mike, 

I'm planning to use this on a project that I'm working on and hoping you're open to a PR.  

I have tried to set up a test, but unfortunately due to where the routing is set up I cannot change the config item so late in the test with any effect.  A possible way around this is to instead define the middleware in the controller, and use the config there (let me know if you'd like me to adjust).

The idea here is that I'd like to use the `password.confirm` middleware in order to ask for a password before a user is able to impersonate.

I've also made the tests work with laravel/ui and legacy factories along the way.

Thanks, 

Keoghan

### CODE REVIEW

**Comment by Keoghan** [comment]
Composer appears to be running out of memory on Travis :(

**Comment by mikebronner** [comment]
Hi @Keoghan :) PRs are most welcome!!! Don't worry about travis not passing, I need to transition this to GitHub actions anyway. Please give me a few days to look over this and test it. :)

**Comment by Keoghan** [comment]
Greatly appreciated @mikebronner - let me know if you need me to do anything

**Comment by mikebronner** [comment]
Thanks @Keoghan !!! Awesome PR, nicely done. :)

**Comment by Keoghan** [comment]
Thanks Mike 🙂

**Comment by mikebronner** [comment]
@Keoghan I spent a little time today sorting out test runners and implementing GitHub Actions, as well as switching from Coveralls to CodeCov. Your changes should now be in release 8.0.1. Let me know how it works for you.
Also, I plan on moving tests to Orchestral/Testbench in the near future. This was written before I got into using your packages. :)

**Comment by Keoghan** [comment]
Looks great, thanks @mikebronner 

Shout if I can help with the switch over to testbench at all 👍

**Pull request merged**
